USE [master]
GO

/****** Object:  Database [DWH_DATA]    Script Date: 5/21/2023 7:51:57 PM ******/
CREATE DATABASE [DWH_DATA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DWH_DATA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.NVKSQLSERVER\MSSQL\DATA\DWH_DATA.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DWH_DATA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.NVKSQLSERVER\MSSQL\DATA\DWH_DATA_log.ldf' , SIZE = 729088KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DWH_DATA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DWH_DATA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DWH_DATA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DWH_DATA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DWH_DATA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DWH_DATA] SET ARITHABORT OFF 
GO

ALTER DATABASE [DWH_DATA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DWH_DATA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DWH_DATA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DWH_DATA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DWH_DATA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DWH_DATA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DWH_DATA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DWH_DATA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DWH_DATA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DWH_DATA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DWH_DATA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DWH_DATA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DWH_DATA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DWH_DATA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DWH_DATA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DWH_DATA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DWH_DATA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DWH_DATA] SET RECOVERY FULL 
GO

ALTER DATABASE [DWH_DATA] SET  MULTI_USER 
GO

ALTER DATABASE [DWH_DATA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DWH_DATA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DWH_DATA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DWH_DATA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DWH_DATA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DWH_DATA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DWH_DATA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DWH_DATA] SET  READ_WRITE 
GO


